# Generated by Django 2.0.8 on 2019-09-25 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=15, verbose_name='昵称')),
                ('sex', models.IntegerField(blank=True, default=1, verbose_name='性别')),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='手机号')),
                ('new_email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('position', models.CharField(blank=True, choices=[(0, 'Android端'), (1, 'IOS端'), (2, 'Test端'), (3, 'Web端'), (4, '服务端')], max_length=1, verbose_name='所属端')),
                ('remarks', models.CharField(blank=True, max_length=150, verbose_name='备注')),
                ('pic', models.ImageField(blank=True, upload_to='img', verbose_name='头像')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户扩展',
                'verbose_name_plural': '用户扩展',
                'ordering': ['id'],
            },
        ),
    ]
